# Generated by Django 5.2 on 2025-04-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0001_initial'),
    ]

    operations = [
    ]
