# Generated by Django 5.2 on 2025-05-13 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0005_remove_tarea_estado_proyecto_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios asignados a este proyecto', related_name='proyectos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
