# Generated by Django 5.2 on 2025-05-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0006_proyecto_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
