# Generated by Django 5.2 on 2025-05-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0008_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
